[package]
name = "core-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
configparser = "3.0.2"
core = { path = "../core" }
mockall = "0.11.3"
sqlite = "0.30.4"
